/**
 * This header is generated by class-dump-z 0.2-1.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

#import "QuartzCore-Structs.h"
#import <QuartzCore/CABase.h>

@interface CAFilter : NSObject <NSCopying, NSMutableCopying, NSCoding>

@property (readonly) NSString *type;
@property (copy) NSString *name;
@property (getter=isEnabled) BOOL enabled;
@property BOOL cachesInputImage;
// ["multiplyColor","multiplyGradient","gaussianBlur","pageCurl","fog","lighting","clear","copy",
//  "sourceOver","sourceIn","sourceOut","sourceAtop","destOver","destIn","destOut","destAtop","xor","plusL","multiply"]
+ (NSArray<NSString *> *)filterTypes;
+ (CAFilter *)filterWithType:(NSString *)type;
+ (CAFilter *)filterWithName:(NSString *)name;

- (instancetype)initWithType:(NSString *)type;
- (instancetype)initWithName:(NSString *)name;

- (BOOL)enabled;
- (void)setValue:(id)value forKey:(id)key;
- (id)valueForKey:(id)key;
- (void)setDefaults;
- (Object *)CA_copyRenderValue;
- (void)willChangeValueForKey:(id)key;
- (void)didChangeValueForKey:(id)key;

@end

CA_EXTERN NSString *const kCAFilterClear;
CA_EXTERN NSString *const kCAFilterCopy;
CA_EXTERN NSString *const kCAFilterDestAtop;
CA_EXTERN NSString *const kCAFilterDestIn;
CA_EXTERN NSString *const kCAFilterDestOut;
CA_EXTERN NSString *const kCAFilterDestOver;
CA_EXTERN NSString *const kCAFilterFog;
CA_EXTERN NSString *const kCAFilterGaussianBlur;
CA_EXTERN NSString *const kCAFilterLanczos;
CA_EXTERN NSString *const kCAFilterLighting;
CA_EXTERN NSString *const kCAFilterLinear;
CA_EXTERN NSString *const kCAFilterMultiply;
CA_EXTERN NSString *const kCAFilterMultiplyColor;
CA_EXTERN NSString *const kCAFilterMultiplyGradient;
CA_EXTERN NSString *const kCAFilterNearest;
CA_EXTERN NSString *const kCAFilterPageCurl;
CA_EXTERN NSString *const kCAFilterPlusL;
CA_EXTERN NSString *const kCAFilterSourceAtop;
CA_EXTERN NSString *const kCAFilterSourceIn;
CA_EXTERN NSString *const kCAFilterSourceOut;
CA_EXTERN NSString *const kCAFilterSourceOver;
CA_EXTERN NSString *const kCAFilterTrilinear;
CA_EXTERN NSString *const kCAFilterXor;
