/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Cydia/FilteredPackageListController.h>

@interface ChangesController : FilteredPackageListController {

	unsigned upgrades_;

}
-(id)navigationURL;
-(id)referrerURL;
-(id)packageAtIndexPath:(id)arg1 ;
-(BOOL)shouldYield;
-(BOOL)shouldBlock;
-(id)sectionsForPackages:(id)arg1 ;
-(void)refreshButtonClicked;
-(void)setLeftBarButtonItem;
-(void)useFilter;
-(void)upgradeButtonClicked;
-(id)initWithDatabase:(id)arg1 ;
-(void)reloadData;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidLoad;
-(void)cancelButtonClicked;
@end

