/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <Cydia/CydiaWebViewController.h>

@class Database;

@interface ConfirmationController : CydiaWebViewController {

	Database* database_;
	char substrate_;

}
-(void)applyRightButton;
-(void)_doContinue;
-(void)confirmButtonClicked;
-(id)initWithDatabase:(id)arg1 ;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(void)webView:(id)arg1 didClearWindowObject:(id)arg2 forFrame:(id)arg3 ;
-(void)complete;
-(void)cancelButtonClicked;
-(id)invokeDefaultMethodWithArguments:(id)arg1 ;
-(id)leftButton;
@end

