/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@protocol CydiaDelegate
@required
-(void)releaseNetworkActivityIndicator;
-(void)retainNetworkActivityIndicator;
-(void)reloadDataWithInvocation:(id)arg1;
-(void)addTrivialSource:(id)arg1;
-(void)installPackages:(id)arg1;
-(void)_saveConfig;
-(void)returnToCydia;
-(id)addProgressHUD;
-(void)clearPackage:(id)arg1;
-(void)installPackage:(id)arg1;
-(void)removePackage:(id)arg1;
-(void)showActionSheet:(id)arg1 fromItem:(id)arg2;
-(void)removeProgressHUD:(id)arg1;
-(void)updateData;
-(void)distUpgrade;
-(void)addSource:(id)arg1;
-(char)updating;
-(void)beginUpdate;
-(void)saveState;
-(BOOL)requestUpdate;
-(void)loadData;
-(void)syncData;

@end

