/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


#import <Cydia/Cydia-Structs.h>
@interface CydiaObject : NSObject {

	MenesObjectHandle<CyteWebViewController, 0> indirect_;
	id delegate_;

}
+(id)_attributeKeys;
+(char)isSelectorExcludedFromWebScript:(SEL)arg1 ;
+(id)webScriptNameForSelector:(SEL)arg1 ;
+(char)isKeyExcludedFromWebScript:(const char*)arg1 ;
-(void)setViewportWidth:(float)arg1 ;
-(void)setAllowsNavigationAction:(id)arg1 ;
-(void)setHidesNavigationBar:(id)arg1 ;
-(void)setScrollAlwaysBounceVertical:(id)arg1 ;
-(void)setScrollIndicatorStyle:(id)arg1 ;
-(void)setButtonImage:(id)arg1 withStyle:(id)arg2 toFunction:(id)arg3 ;
-(void)setButtonTitle:(id)arg1 withStyle:(id)arg2 toFunction:(id)arg3 ;
-(void)removeButton;
-(void)setNavigationBarStyle:(id)arg1 ;
-(void)registerFrame:(id)arg1 ;
-(void)addBridgedHost:(id)arg1 ;
-(void)addInsecureHost:(id)arg1 ;
-(void)addInternalRedirect:(id)arg1 :(id)arg2 ;
-(void)addPipelinedHost:(id)arg1 scheme:(id)arg2 ;
-(void)addSource:(id)arg1 :(id)arg2 :(id)arg3 ;
-(void)addTrivialSource:(id)arg1 ;
-(id)du:(id)arg1 ;
-(id)getAllSources;
-(id)getApplicationInfo:(id)arg1 value:(id)arg2 ;
-(id)getKernelNumber:(id)arg1 ;
-(id)getKernelString:(id)arg1 ;
-(id)getInstalledPackages;
-(id)getIORegistryEntry:(id)arg1 :(id)arg2 ;
-(id)getLocaleIdentifier;
-(id)getPreferredLanguages;
-(id)getPackageById:(id)arg1 ;
-(id)getMetadataKeys;
-(id)getMetadataValue:(id)arg1 ;
-(id)getSessionValue:(id)arg1 ;
-(void)installPackages:(id)arg1 ;
-(id)isReachable:(id)arg1 ;
-(void)popViewController:(id)arg1 ;
-(void)refreshSources;
-(void)saveConfig;
-(void)setMetadataValue:(id)arg1 :(id)arg2 ;
-(void)setSessionValue:(id)arg1 :(id)arg2 ;
-(id)substitutePackageNames:(id)arg1 ;
-(void)scrollToBottom:(id)arg1 ;
-(void)setNavigationBarTintRed:(id)arg1 green:(id)arg2 blue:(id)arg3 alpha:(id)arg4 ;
-(void)setPasteboardString:(id)arg1 ;
-(void)setPasteboardURL:(id)arg1 ;
-(id)statfs:(id)arg1 ;
-(char)supports:(id)arg1 ;
-(id)coreFoundationVersionNumber;
-(id)firmware;
-(id)mcc;
-(id)mnc;
-(id)bbsnum;
-(id)ecid;
-(id)serial;
-(id)build;
-(id)role;
-(void)setDelegate:(id)arg1 ;
-(id)localizedStringForKey:(id)arg1 value:(id)arg2 table:(id)arg3 ;
-(void)setHidesBackButton:(id)arg1 ;
-(id)model;
-(void)setBadgeValue:(id)arg1 ;
-(id)idiom;
-(void)close;
-(id)version;
-(void)setToken:(id)arg1 ;
-(id)operator;
-(void)unload;
-(id)stringWithFormat:(id)arg1 arguments:(id)arg2 ;
-(id)initWithDelegate:(id)arg1 ;
-(id)device;
-(id)hostname;
-(id)attributeKeys;
@end

