/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <Cydia/CyteTabBarController.h>
#import <UIKit/UITabBarControllerDelegate.h>
#import <Cydia/FetchDelegate.h>

@protocol CydiaDelegate;
@class Database, NSObject;

@interface CydiaTabBarController : CyteTabBarController <UITabBarControllerDelegate, FetchDelegate> {

	Database* database_;
	MenesObjectHandle<UIActivityIndicatorView, 0> indicator_;
	BOOL updating_;
	NSObject*<CydiaDelegate> updatedelegate_;

}
-(id)navigationURLCollection;
-(void)completeUpdate;
-(void)stopUpdateWithSelector:(SEL)arg1 ;
-(void)cancelUpdate;
-(BOOL)isSourceCancelled;
-(void)startSourceFetch:(id)arg1 ;
-(void)stopSourceFetch:(id)arg1 ;
-(void)setUpdateDelegate:(id)arg1 ;
-(char)updating;
-(id)initWithDatabase:(id)arg1 ;
-(void)beginUpdate;
-(void)cancelPressed;
-(void)performUpdate;
@end

