/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


#import <Cydia/Cydia-Structs.h>
@interface CydiaOperation : NSObject {

	MenesObjectHandle<NSString, 0> operator_;
	MenesObjectHandle<NSString, 0> value_;

}
+(id)_attributeKeys;
+(char)isKeyExcludedFromWebScript:(const char*)arg1 ;
-(id)initWithOperator:(const char*)arg1 value:(const char*)arg2 ;
-(id)value;
-(id)operator;
-(id)attributeKeys;
@end

