/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


#import <Cydia/Cydia-Structs.h>
@interface CydiaProgressData : NSObject {

	id delegate_;
	BOOL running_;
	float percent_;
	float current_;
	float total_;
	float speed_;
	MenesObjectHandle<NSMutableArray, 0> events_;
	MenesObjectHandle<NSString, 0> title_;
	MenesObjectHandle<NSString, 0> status_;
	MenesObjectHandle<NSString, 0> finish_;

}
+(id)_attributeKeys;
+(char)isKeyExcludedFromWebScript:(const char*)arg1 ;
-(void)removeAllEvents;
-(void)setFinish:(id)arg1 ;
-(void)addEvent:(id)arg1 ;
-(void)setTotal:(float)arg1 ;
-(id)events;
-(void)setDelegate:(id)arg1 ;
-(id)init;
-(void)setTitle:(id)arg1 ;
-(id)delegate;
-(void)setSpeed:(float)arg1 ;
-(id)title;
-(id)speed;
-(id)finish;
-(id)percent;
-(void)setPercent:(float)arg1 ;
-(void)setRunning:(BOOL)arg1 ;
-(id)current;
-(void)setCurrent:(float)arg1 ;
-(id)running;
-(id)total;
-(id)attributeKeys;
@end

