/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import "ProgressDelegate.h"

@class UIViewController, CyteTableViewCellContentView, UIColor, CyteWebView, UIActivityIndicatorView, IndirectDelegate, NSURLAuthenticationChallenge, NSURLRequest, NSURL, NSString, NSMutableSet, NSTimer, NSObject, WebScriptObject, UIBarButtonItem, UILabel, UIView, NSArray, NSMutableDictionary, CydiaOperation, NSMutableArray, Source, NSDate, CyteWebViewController, CydiaObject, UIAlertView, NSDictionary, CydiaProgressData, UIImage, UISwitch, Package, UITableView, UISearchBar, UITableViewCell, UIProgressHUD, NSError, UIWindow, CydiaTabBarController, CyteTabBarController, AppCacheController, StashController;

typedef struct CYString {
	char* data_;
	unsigned size_;
	CFStringRef cache_;
} CYString;

typedef struct VerIterator {
} VerIterator;

typedef struct PkgIterator {
} PkgIterator;

typedef struct VerFileIterator {
} VerFileIterator;

typedef struct CYPool {
	char* data_;
	unsigned size_;
} CYPool;

typedef struct CydiaStatus {
	/*function pointer*/void* _vptr$pkgAcquireStatus;
	timeval Time;
	timeval StartTime;
	double LastBytes;
	double CurrentCPS;
	double CurrentBytes;
	double TotalBytes;
	double FetchedBytes;
	unsigned long ElapsedTime;
	unsigned long TotalItems;
	unsigned long CurrentItems;
	BOOL Update;
	BOOL MorePulses;
	BOOL cancelled_;
	NSObject<ProgressDelegate>* delegate_;
} CydiaStatus;