/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <UIKit/UIApplication.h>
#import <Cydia/ConfirmationControllerDelegate.h>
#import <Cydia/DatabaseDelegate.h>
#import <Cydia/CydiaDelegate.h>

@class Database;

@interface Cydia : UIApplication <ConfirmationControllerDelegate, DatabaseDelegate, CydiaDelegate> {

	Database* database_;
	unsigned locked_;
	unsigned activity_;
	BOOL loaded_;

}
-(void)unloadData;
-(void)releaseNetworkActivityIndicator;
-(id)pageForURL:(id)arg1 forExternal:(char)arg2 withReferrer:(id)arg3 ;
-(void)retainNetworkActivityIndicator;
-(void)setConfigurationData:(id)arg1 ;
-(void)addProgressEventOnMainThread:(id)arg1 forTask:(id)arg2 ;
-(void)repairWithSelector:(SEL)arg1 ;
-(void)reloadDataWithInvocation:(id)arg1 ;
-(void)addTrivialSource:(id)arg1 ;
-(void)installPackages:(id)arg1 ;
-(void)_saveConfig;
-(void)confirmWithNavigationController:(id)arg1 ;
-(void)cancelAndClear:(BOOL)arg1 ;
-(void)returnToCydia;
-(id)addProgressHUD;
-(void)clearPackage:(id)arg1 ;
-(void)installPackage:(id)arg1 ;
-(void)removePackage:(id)arg1 ;
-(void)showActionSheet:(id)arg1 fromItem:(id)arg2 ;
-(void)removeProgressHUD:(id)arg1 ;
-(void)updateDataAndLoad;
-(void)cancelUpdate;
-(void)updateData;
-(void)distUpgrade;
-(void)_loaded;
-(id)queueNavigationController;
-(void)_refreshIfPossible;
-(void)_updateData;
-(void)disemulate;
-(void)presentModalViewController:(id)arg1 force:(char)arg2 ;
-(id)invokeNewProgress:(id)arg1 forController:(id)arg2 withTitle:(id)arg3 ;
-(void)repairWithInvocation:(id)arg1 ;
-(void)update_;
-(void)detachNewProgressSelector:(SEL)arg1 toTarget:(id)arg2 forController:(id)arg3 title:(id)arg4 ;
-(void)_uicache;
-(void)uicache;
-(void)lockSuspend;
-(void)perform_;
-(void)unlockSuspend;
-(char)isSafeToSuspend;
-(void)_animateSuspension:(char)arg1 duration:(double)arg2 startTime:(double)arg3 scale:(float)arg4 ;
-(id)pageForPackage:(id)arg1 withReferrer:(id)arg2 ;
-(char)openCydiaURL:(id)arg1 forExternal:(char)arg2 ;
-(void)system:(id)arg1 ;
-(void)removeStashController;
-(void)_sendMemoryWarningNotification;
-(void)addStashController;
-(void)refreshIfPossible;
-(id)defaultStartPages;
-(void)addProgressEvent:(id)arg1 forTask:(id)arg2 ;
-(void)addProgressEventForTask:(id)arg1 ;
-(void)addSource:(id)arg1 withDistribution:(id)arg2 andSections:(id)arg3 ;
-(void)_sendMemoryWarningNotifications;
-(void)setupViewControllers;
-(void)resolve;
-(void)addSource:(id)arg1 ;
-(char)updating;
-(void)beginUpdate;
-(void)saveState;
-(void)reloadData;
-(void)applicationDidReceiveMemoryWarning:(id)arg1 ;
-(void)applicationWillTerminate:(id)arg1 ;
-(void)applicationWillResignActive:(id)arg1 ;
-(void)applicationDidEnterBackground:(id)arg1 ;
-(void)applicationWillEnterForeground:(id)arg1 ;
-(void)applicationDidFinishLaunching:(id)arg1 ;
-(void)applicationWillSuspend;
-(void)_setSuspended:(char)arg1 ;
-(void)suspendReturningToLastApp:(char)arg1 ;
-(void)applicationSuspend;
-(void)applicationOpenURL:(id)arg1 ;
-(void)suspend;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(void)stash;
-(BOOL)perform;
-(void)queue;
-(BOOL)requestUpdate;
-(void)loadData;
-(void)syncData;
@end

