/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <Cydia/CydiaWebViewController.h>

@class Database;

@interface CYPackageController : CydiaWebViewController <UIActionSheetDelegate> {

	Database* database_;
	BOOL commercial_;

}
-(id)navigationURL;
-(void)setPageColor:(id)arg1 ;
-(BOOL)_allowJavaScriptPanel;
-(void)applyLoadingTitle;
-(void)reloadButtonClicked;
-(void)_customButtonClicked;
-(void)_clickButtonWithName:(id)arg1 ;
-(id)initWithDatabase:(id)arg1 forPackage:(id)arg2 withReferrer:(id)arg3 ;
-(void)reloadData;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(BOOL)isLoading;
-(id)rightButton;
@end

