/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <Cydia/CyteViewController.h>
#import <Cydia/CyteWebViewDelegate.h>
#import <Cydia/MFMailComposeViewControllerDelegate.h>

@class UIScrollView, NSNumber;

@interface CyteWebViewController : CyteViewController <CyteWebViewDelegate, MFMailComposeViewControllerDelegate, UIWebViewDelegate> {

	UIScrollView* scroller_;
	BOOL error_;
	BOOL ready_;
	NSNumber* sensitive_;
	float width_;
	Class class_;
	BOOL visible_;
	BOOL hidesNavigationBar_;
	BOOL allowsNavigationAction_;

}
+(void)_lockJavaScript:(id)arg1 ;
+(float)defaultWidth;
+(void)_initialize;
-(void)releaseSubviews;
-(void)webView:(id)arg1 didDecidePolicy:(int)arg2 forNavigationAction:(id)arg3 request:(id)arg4 frame:(id)arg5 ;
-(BOOL)webView:(id)arg1 shouldRunJavaScriptAlertPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 ;
-(BOOL)webView:(id)arg1 shouldRunJavaScriptConfirmPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 ;
-(BOOL)webView:(id)arg1 shouldRunJavaScriptTextInputPanelWithPrompt:(id)arg2 defaultText:(id)arg3 initiatedByFrame:(id)arg4 ;
-(void)webViewUpdateViewSettings:(id)arg1 ;
-(BOOL)retainsNetworkActivityIndicator;
-(void)releaseNetworkActivityIndicator;
-(id)URLWithURL:(id)arg1 ;
-(void)setURL:(id)arg1 withReferrer:(id)arg2 ;
-(id)requestWithURL:(id)arg1 cachePolicy:(unsigned)arg2 referrer:(id)arg3 ;
-(void)loadURL:(id)arg1 cachePolicy:(unsigned)arg2 ;
-(void)reloadURLWithCache:(char)arg1 ;
-(void)applyRightButton;
-(void)_setViewportWidth;
-(void)setViewportWidth:(float)arg1 ;
-(void)_setViewportWidthOnMainThread:(id)arg1 ;
-(void)_setupMail:(id)arg1 ;
-(void)setAllowsNavigationAction:(BOOL)arg1 ;
-(void)_didFinishLoading;
-(BOOL)allowsNavigationAction;
-(void)pushRequest:(id)arg1 forAction:(id)arg2 asPop:(BOOL)arg3 ;
-(void)_openMailToURL:(id)arg1 ;
-(void)_didFailWithError:(id)arg1 forFrame:(id)arg2 ;
-(void)setHidesNavigationBar:(BOOL)arg1 ;
-(void)setScrollAlwaysBounceVertical:(BOOL)arg1 ;
-(void)setScrollIndicatorStyle:(int)arg1 ;
-(void)_didStartLoading;
-(BOOL)_allowJavaScriptPanel;
-(int)rightButtonStyle;
-(void)customButtonClicked;
-(void)layoutRightButton;
-(void)applyLoadingTitle;
-(id)customButton;
-(void)didStartLoading;
-(void)didFinishLoading;
-(void)reloadButtonClicked;
-(void)applyLeftButton;
-(id)initWithWidth:(float)arg1 ofClass:(Class)arg2 ;
-(id)initWithWidth:(float)arg1 ;
-(void)callFunction:(id)arg1 ;
-(void)_customButtonClicked;
-(BOOL)hidesNavigationBar;
-(void)_setHidesNavigationBar:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)updateHeights:(id)arg1 ;
-(void)setButtonImage:(id)arg1 withStyle:(id)arg2 toFunction:(id)arg3 ;
-(void)setButtonTitle:(id)arg1 withStyle:(id)arg2 toFunction:(id)arg3 ;
-(void)removeButton;
-(void)scrollToBottomAnimated:(id)arg1 ;
-(void)setViewportWidthOnMainThread:(float)arg1 ;
-(void)setAllowsNavigationActionByNumber:(id)arg1 ;
-(void)popViewControllerWithNumber:(id)arg1 ;
-(void)setNavigationBarStyle:(id)arg1 ;
-(void)setHidesBackButtonByNumber:(id)arg1 ;
-(void)setHidesNavigationBarByNumber:(id)arg1 ;
-(void)setScrollAlwaysBounceVerticalNumber:(id)arg1 ;
-(void)setScrollIndicatorStyleWithName:(id)arg1 ;
-(void)registerFrame:(id)arg1 ;
-(void)dealloc;
-(void)reloadData;
-(id)init;
-(id)description;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(void)setHidesBackButton:(BOOL)arg1 ;
-(void)setNavigationBarTintColor:(id)arg1 ;
-(void)loadView;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidAppear:(char)arg1 ;
-(void)viewWillDisappear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(id)initWithURL:(id)arg1 ;
-(void)setBadgeValue:(id)arg1 ;
-(id)webView;
-(void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 request:(id)arg3 frame:(id)arg4 decisionListener:(id)arg5 ;
-(void)close;
-(void)loadRequest:(id)arg1 ;
-(void)webView:(id)arg1 didFinishLoadForFrame:(id)arg2 ;
-(void)webView:(id)arg1 didFailLoadWithError:(id)arg2 forFrame:(id)arg3 ;
-(void)webView:(id)arg1 didCommitLoadForFrame:(id)arg2 ;
-(BOOL)isLoading;
-(void)setURL:(id)arg1 ;
-(void)webView:(id)arg1 decidePolicyForNewWindowAction:(id)arg2 request:(id)arg3 newFrameName:(id)arg4 decisionListener:(id)arg5 ;
-(void)webView:(id)arg1 didStartProvisionalLoadForFrame:(id)arg2 ;
-(void)webView:(id)arg1 didReceiveTitle:(id)arg2 forFrame:(id)arg3 ;
-(id)webThreadWebView:(id)arg1 resource:(id)arg2 willSendRequest:(id)arg3 redirectResponse:(id)arg4 fromDataSource:(id)arg5 ;
-(void)webView:(id)arg1 didClearWindowObject:(id)arg2 forFrame:(id)arg3 ;
-(void)webView:(id)arg1 didFailProvisionalLoadWithError:(id)arg2 forFrame:(id)arg3 ;
-(void)webViewClose:(id)arg1 ;
-(void)webView:(id)arg1 resource:(id)arg2 didReceiveAuthenticationChallenge:(id)arg3 fromDataSource:(id)arg4 ;
-(id)initWithRequest:(id)arg1 ;
-(void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3 ;
-(id)applicationNameForUserAgent;
-(void)loadURL:(id)arg1 ;
-(id)webView:(id)arg1 resource:(id)arg2 willSendRequest:(id)arg3 redirectResponse:(id)arg4 fromDataSource:(id)arg5 ;
-(void)setRequest:(id)arg1 ;
-(void)dispatchEvent:(id)arg1 ;
-(void)webView:(id)arg1 addMessageToConsole:(id)arg2 ;
-(id)leftButton;
-(id)rightButton;
@end

