/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <UIKit/UITabBarController.h>

@class UIViewController;

@interface CyteTabBarController : UITabBarController {

	UIViewController* transient_;
	MenesObjectHandle<UIViewController, 0> remembered_;

}
-(id)unselectedViewController;
-(void)setUnselectedViewController:(id)arg1 ;
-(void)unloadData;
-(void)didReceiveMemoryWarning;
-(char)shouldAutorotate;
-(unsigned)supportedInterfaceOrientations;
-(char)shouldAutorotateToInterfaceOrientation:(int)arg1 ;
-(void)dismissModalViewControllerAnimated:(char)arg1 ;
-(void)tabBarController:(id)arg1 didSelectViewController:(id)arg2 ;
@end

