/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <UIKit/UIViewController.h>

@interface CyteViewController : UIViewController {

	id delegate_;
	char loaded_;

}
-(void)unloadData;
-(void)releaseSubviews;
-(id)navigationURL;
-(void)setPageColor:(id)arg1 ;
-(void)setDelegate:(id)arg1 ;
-(void)reloadData;
-(id)delegate;
-(char)shouldAutorotate;
-(unsigned)supportedInterfaceOrientations;
-(void)setView:(id)arg1 ;
-(char)shouldAutorotateToInterfaceOrientation:(int)arg1 ;
-(void)viewWillAppear:(char)arg1 ;
-(char)hasLoaded;
@end

