/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <Cydia/CyteViewController.h>
#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UITableViewDelegate.h>

@class Database;

@interface PackageSettingsController : CyteViewController <UITableViewDataSource, UITableViewDelegate> {

	Database* database_;
	MenesObjectHandle<NSString, 0> name_;
	MenesObjectHandle<Package, 0> package_;
	MenesObjectHandle<UITableView, 2> table_;
	MenesObjectHandle<UISwitch, 0> subscribedSwitch_;
	MenesObjectHandle<UISwitch, 0> ignoredSwitch_;
	MenesObjectHandle<UITableViewCell, 0> subscribedCell_;
	MenesObjectHandle<UITableViewCell, 0> ignoredCell_;

}
-(void)releaseSubviews;
-(id)navigationURL;
-(void)_updateIgnored;
-(void)onSubscribed:(id)arg1 ;
-(void)onIgnored:(id)arg1 ;
-(id)initWithDatabase:(id)arg1 package:(id)arg2 ;
-(void)reloadData;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2 ;
-(id)tableView:(id)arg1 titleForFooterInSection:(int)arg2 ;
-(void)loadView;
-(void)viewDidLoad;
@end

