/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <Cydia/CyteViewController.h>

@class Database;

@interface PackageListController : CyteViewController <UITableViewDataSource, UITableViewDelegate> {

	Database* database_;
	unsigned era_;
	unsigned reloading_;

}
-(void)releaseSubviews;
-(void)resizeForKeyboardBounds:(CGRect)arg1 duration:(double)arg2 curve:(int)arg3 ;
-(void)resizeForKeyboardBounds:(CGRect)arg1 duration:(double)arg2 ;
-(void)getKeyboardCurve:(int*)arg1 duration:(double*)arg2 forNotification:(id)arg3 ;
-(void)resizeForKeyboardBounds:(CGRect)arg1 ;
-(void)deselectWithAnimation:(char)arg1 ;
-(id)referrerURL;
-(id)packageAtIndexPath:(id)arg1 ;
-(BOOL)isSummarized;
-(void)didSelectPackage:(id)arg1 ;
-(void)updateHeight;
-(BOOL)shouldYield;
-(BOOL)shouldBlock;
-(id)_reloadPackages;
-(BOOL)showsSections;
-(id)sectionsForPackages:(id)arg1 ;
-(void)resetCursor;
-(id)initWithDatabase:(id)arg1 title:(id)arg2 ;
-(void)setDelegate:(id)arg1 ;
-(void)reloadData;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2 ;
-(id)sectionIndexTitlesForTableView:(id)arg1 ;
-(int)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(int)arg3 ;
-(void)loadView;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidAppear:(char)arg1 ;
-(void)viewWillDisappear:(char)arg1 ;
-(void)_reloadData;
-(void)clearData;
-(void)keyboardWillShow:(id)arg1 ;
-(void)keyboardWillHide:(id)arg1 ;
@end

