/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <Cydia/CydiaWebViewController.h>
#import <Cydia/ProgressDelegate.h>

@class Database;

@interface ProgressController : CydiaWebViewController <ProgressDelegate> {

	Database* database_;
	unsigned cancel_;

}
-(void)addProgressEvent:(id)arg1 ;
-(void)setProgressPercent:(id)arg1 ;
-(void)updateCancel;
-(void)reloadSpringBoard;
-(void)setProgressStatus:(id)arg1 ;
-(void)setProgressCancellable:(id)arg1 ;
-(BOOL)isProgressCancelled;
-(id)initWithDatabase:(id)arg1 delegate:(id)arg2 ;
-(void)invoke:(id)arg1 withTitle:(id)arg2 ;
-(void)cancel;
-(void)dealloc;
-(void)setTitle:(id)arg1 ;
-(void)viewWillAppear:(char)arg1 ;
-(void)close;
-(void)webView:(id)arg1 didClearWindowObject:(id)arg2 forFrame:(id)arg3 ;
-(void)updateProgress;
-(void)setCancellable:(BOOL)arg1 ;
-(id)leftButton;
-(id)rightButton;
@end

