/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <CFNetwork/NSURLCache.h>

@class NSString, NSMutableDictionary, NSOperationQueue, NSTimer, NSOperation;

@interface SDURLCache : NSURLCache {

	NSString* diskCachePath;
	NSMutableDictionary* diskCacheInfo;
	char diskCacheInfoDirty;
	char ignoreMemoryOnlyStoragePolicy;
	char breakURLCacheCompatibility;
	unsigned diskCacheUsage;
	double minCacheInterval;
	NSOperationQueue* ioQueue;
	NSTimer* periodicMaintenanceTimer;
	NSOperation* periodicMaintenanceOperation;

}

@property (assign,nonatomic) double minCacheInterval; 
@property (assign,nonatomic) char ignoreMemoryOnlyStoragePolicy; 
@property (assign,nonatomic) char breakURLCacheCompatibility; 
@property (nonatomic,retain) NSString * diskCachePath; 
@property (nonatomic,readonly) NSMutableDictionary * diskCacheInfo; 
@property (nonatomic,retain) NSOperationQueue * ioQueue; 
@property (retain) NSOperation * periodicMaintenanceOperation; 
+(id)dateFromHttpDateString:(id)arg1 ;
+(id)cacheKeyForURL:(id)arg1 ;
+(id)expirationDateFromHeaders:(id)arg1 withStatusCode:(int)arg2 ;
+(id)defaultCachePath;
+(id)canonicalRequestForRequest:(id)arg1 ;
-(void)periodicMaintenance;
-(void)createDiskCachePath;
-(NSMutableDictionary *)diskCacheInfo;
-(void)removeCachedResponseForCachedKeys:(id)arg1 ;
-(void)saveCacheInfo;
-(void)setPeriodicMaintenanceOperation:(NSOperation *)arg1 ;
-(void)balanceDiskUsage;
-(void)setMinCacheInterval:(double)arg1 ;
-(void)setIoQueue:(NSOperationQueue *)arg1 ;
-(void)setIgnoreMemoryOnlyStoragePolicy:(char)arg1 ;
-(void)setBreakURLCacheCompatibility:(char)arg1 ;
-(void)logEvent:(id)arg1 forRequest:(id)arg2 ;
-(void)storeToDisk:(id)arg1 ;
-(NSString *)diskCachePath;
-(char)isCached:(id)arg1 ;
-(double)minCacheInterval;
-(NSOperationQueue *)ioQueue;
-(NSOperation *)periodicMaintenanceOperation;
-(char)ignoreMemoryOnlyStoragePolicy;
-(char)breakURLCacheCompatibility;
-(unsigned)currentDiskUsage;
-(id)initWithMemoryCapacity:(unsigned)arg1 diskCapacity:(unsigned)arg2 diskPath:(id)arg3 ;
-(void)removeCachedResponseForRequest:(id)arg1 ;
-(id)cachedResponseForRequest:(id)arg1 ;
-(void)storeCachedResponse:(id)arg1 forRequest:(id)arg2 ;
-(void)dealloc;
-(void)setDiskCachePath:(NSString *)arg1 ;
-(void)removeAllCachedResponses;
@end

