/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <Cydia/FilteredPackageListController.h>
#import <UIKit/UISearchBarDelegate.h>

@interface SearchController : FilteredPackageListController <UISearchBarDelegate> {

	MenesObjectHandle<UISearchBar, 1> search_;
	char searchloaded_;
	BOOL summary_;

}
-(id)navigationURL;
-(id)referrerURL;
-(BOOL)isSummarized;
-(void)didSelectPackage:(id)arg1 ;
-(BOOL)shouldYield;
-(BOOL)shouldBlock;
-(BOOL)showsSections;
-(id)termsForQuery:(id)arg1 ;
-(void)usePrefix:(id)arg1 ;
-(void)useSearch;
-(void)searchBarButtonClicked:(id)arg1 ;
-(void)reloadData;
-(void)viewDidAppear:(char)arg1 ;
-(void)searchBar:(id)arg1 textDidChange:(id)arg2 ;
-(void)searchBarCancelButtonClicked:(id)arg1 ;
-(void)searchBarTextDidBeginEditing:(id)arg1 ;
-(void)searchBarSearchButtonClicked:(id)arg1 ;
-(id)initWithDatabase:(id)arg1 query:(id)arg2 ;
@end

