/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


#import <Cydia/Cydia-Structs.h>
@interface Section : NSObject {

	MenesObjectHandle<NSString, 0> name_;
	unsigned long row_;
	unsigned long count_;
	MenesObjectHandle<NSString, 0> localized_;

}
-(id)localized;
-(id)initWithName:(id)arg1 localize:(char)arg2 ;
-(id)initWithName:(id)arg1 row:(unsigned long)arg2 localize:(char)arg3 ;
-(int)compareByLocalized:(id)arg1 ;
-(id)initWithName:(id)arg1 localized:(id)arg2 ;
-(void)addToRow;
-(void)addToCount;
-(unsigned long)count;
-(unsigned long)row;
-(void)setName:(id)arg1 ;
-(id)name;
-(void)setCount:(unsigned long)arg1 ;
@end

