/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <Cydia/CyteTableViewCell.h>
#import <Cydia/CyteTableViewCellDelegate.h>

@interface SectionCell : CyteTableViewCell <CyteTableViewCellDelegate> {

	MenesObjectHandle<NSString, 0> basic_;
	MenesObjectHandle<NSString, 0> section_;
	MenesObjectHandle<NSString, 0> name_;
	MenesObjectHandle<NSString, 0> count_;
	MenesObjectHandle<UIImage, 0> icon_;
	MenesObjectHandle<UISwitch, 0> switch_;
	char editing_;

}
-(void)drawContentRect:(CGRect)arg1 ;
-(void)onSwitch:(id)arg1 ;
-(void)setSection:(id)arg1 editing:(char)arg2 ;
-(void)setFrame:(CGRect)arg1 ;
-(id)accessibilityLabel;
-(id)initWithFrame:(CGRect)arg1 reuseIdentifier:(id)arg2 ;
@end

