/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <Cydia/FilteredPackageListController.h>

@interface SectionController : FilteredPackageListController {

	MenesObjectHandle<NSString, 0> key_;
	MenesObjectHandle<NSString, 0> section_;

}
-(id)navigationURL;
-(id)referrerURL;
-(id)initWithDatabase:(id)arg1 source:(id)arg2 section:(id)arg3 ;
-(void)reloadData;
@end

