/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <Cydia/CyteTableViewCell.h>
#import <Cydia/CyteTableViewCellDelegate.h>
#import <Cydia/SourceDelegate.h>

@interface SourceCell : CyteTableViewCell <CyteTableViewCellDelegate, SourceDelegate> {

	MenesObjectHandle<Source, 1> source_;
	MenesObjectHandle<NSURL, 0> url_;
	MenesObjectHandle<UIImage, 0> icon_;
	MenesObjectHandle<NSString, 0> origin_;
	MenesObjectHandle<NSString, 0> label_;
	MenesObjectHandle<UIActivityIndicatorView, 0> indicator_;

}
-(void)drawContentRect:(CGRect)arg1 ;
-(void)setFetch:(id)arg1 ;
-(void)setAllSource;
-(void)_setSource:(id)arg1 ;
-(void)_setImage:(id)arg1 ;
-(void)layoutSubviews;
-(id)accessibilityLabel;
-(id)initWithFrame:(CGRect)arg1 reuseIdentifier:(id)arg2 ;
-(void)setSource:(id)arg1 ;
@end

