/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 3, 2015 at 6:37:31 AM Central European Summer Time
* Operating System: Version 8.3 (Build 12F70)
* Image Source: /private/var/db/stash/_.2t7K5z/Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@protocol UISearchBarDelegate <UIBarPositioningDelegate>
@optional
-(void)searchBar:(id)arg1 textDidChange:(id)arg2;
-(void)searchBar:(id)arg1 selectedScopeButtonIndexDidChange:(int)arg2;
-(char)searchBarShouldBeginEditing:(id)arg1;
-(char)searchBarShouldEndEditing:(id)arg1;
-(void)searchBarCancelButtonClicked:(id)arg1;
-(void)searchBarBookmarkButtonClicked:(id)arg1;
-(void)searchBarResultsListButtonClicked:(id)arg1;
-(void)searchBarTextDidBeginEditing:(id)arg1;
-(void)searchBarTextDidEndEditing:(id)arg1;
-(void)searchBarSearchButtonClicked:(id)arg1;
-(char)searchBar:(id)arg1 shouldChangeTextInRange:(NSRange)arg2 replacementText:(id)arg3;

@end

