/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 22, 2018 at 11:13:54 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /System/Library/PrivateFrameworks/TVSettingKit.framework/TVSettingKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import "TSKPreviewingDelegate.h"
#import "_TSKAnimatorDelegate.h"
#import <UIKit/UINavigationControllerDelegate.h>

@protocol TSKPreviewing;
@class UINavigationController, UIViewController, UIView, NSString;

@interface _TSKSplitViewController : UIViewController <TSKPreviewingDelegate, _TSKAnimatorDelegate, UINavigationControllerDelegate> {

	BOOL _isAnimatingTransition;
	UINavigationController* _navigationController;
	UIViewController* _previewViewController;
	UIView* _previewContainerView;
	UIViewController*<TSKPreviewing> _previewProvider;

}

@property (assign,nonatomic) BOOL isAnimatingTransition;                                    //@synthesize isAnimatingTransition=_isAnimatingTransition - In the implementation block
@property (nonatomic,readonly) UIView * previewContainerView;                               //@synthesize previewContainerView=_previewContainerView - In the implementation block
@property (nonatomic,retain) UIViewController*<TSKPreviewing> previewProvider;              //@synthesize previewProvider=_previewProvider - In the implementation block
@property (nonatomic,readonly) UINavigationController * navigationController;               //@synthesize navigationController=_navigationController - In the implementation block
@property (nonatomic,readonly) UIViewController * previewViewController;                    //@synthesize previewViewController=_previewViewController - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)preferredFocusEnvironments;
-(UINavigationController *)navigationController;
-(void)viewDidLoad;
-(void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(BOOL)arg3 ;
-(id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4 ;
-(UIView *)previewContainerView;
-(UIViewController *)previewViewController;
-(id)initWithNavigationController:(id)arg1 ;
-(void)previewing:(id)arg1 needsUpdateForItemAtIndexPath:(id)arg2 ;
-(void)animatorDidCompleteTransition:(id)arg1 fromViewController:(id)arg2 toViewController:(id)arg3 ;
-(id)animator:(id)arg1 previewViewControllerForViewController:(id)arg2 ;
-(void)animator:(id)arg1 transitionToPreview:(id)arg2 animated:(BOOL)arg3 ;
-(void)_updatePreviewingWithViewController:(id)arg1 ;
-(BOOL)isAnimatingTransition;
-(void)setPreviewViewController:(id)arg1 animated:(BOOL)arg2 ;
-(void)setIsAnimatingTransition:(BOOL)arg1 ;
-(UIViewController*<TSKPreviewing>)previewProvider;
-(void)setPreviewProvider:(UIViewController*<TSKPreviewing>)arg1 ;
@end

