/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 22, 2018 at 11:13:54 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /System/Library/PrivateFrameworks/TVSettingKit.framework/TVSettingKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol _TSKAnimatorDelegate <NSObject>
@required
-(void)animatorDidCompleteTransition:(id)arg1 fromViewController:(id)arg2 toViewController:(id)arg3;
-(id)animator:(id)arg1 previewViewControllerForViewController:(id)arg2;
-(void)animator:(id)arg1 transitionToPreview:(id)arg2 animated:(BOOL)arg3;

@end

