/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 22, 2018 at 11:13:55 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /System/Library/PrivateFrameworks/TVSettingKit.framework/TVSettingKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SFPasswordSharingServiceDelegate
@required
-(void)service:(id)arg1 receivedNetworkInfo:(id)arg2;
-(BOOL)service:(id)arg1 shouldPromptForNetwork:(id)arg2;

@end

