/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 22, 2018 at 11:13:54 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /System/Library/PrivateFrameworks/TVSettingKit.framework/TVSettingKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface TSKCollectionComparator : NSObject
-(id)_changeForRemovingObjectsFromCollection:(id)arg1 missingFromCollection:(id)arg2 ;
-(id)_changeForInsertingObjectsIntoCollection:(id)arg1 availableInCollection:(id)arg2 ;
-(id)changesFromObjects:(id)arg1 toObjects:(id)arg2 withIdentifierBlock:(/*^block*/id)arg3 ;
@end

