/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 22, 2018 at 11:13:54 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /System/Library/PrivateFrameworks/TVSettingKit.framework/TVSettingKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray;

@interface TSKKonamiCode : NSObject {

	unsigned long long _sequenceIndex;
	NSArray* _sequence;
	SEL _action;

}

@property (nonatomic,copy) NSArray * sequence;              //@synthesize sequence=_sequence - In the implementation block
@property (assign,nonatomic) SEL action;                    //@synthesize action=_action - In the implementation block
+(id)codeWithSequence:(id)arg1 action:(SEL)arg2 ;
-(void)setSequence:(NSArray *)arg1 ;
-(NSArray *)sequence;
-(SEL)action;
-(void)setAction:(SEL)arg1 ;
-(BOOL)validateSequenceWithNextPressType:(long long)arg1 ;
-(long long)nextPressType;
-(void)resetSequence;
@end

