/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 22, 2018 at 11:13:55 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /System/Library/PrivateFrameworks/TVSettingKit.framework/TVSettingKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIAlertController.h>
#import "TSKSettingItemEditingController.h"


@protocol TSKSettingItemEditingControllerDelegate;
@class TSKSettingItem, NSArray, NSString;

@interface TSKMultiValueViewController : UIAlertController <TSKSettingItemEditingController> {

	NSArray* _sortedLocalizedAvailableValues;
	NSArray* _sortedAvailableValues;
	TSKSettingItem* _editingItem;
	id<TSKSettingItemEditingControllerDelegate> _editingDelegate;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,retain) TSKSettingItem * editingItem;                                                    //@synthesize editingItem=_editingItem - In the implementation block
@property (assign,nonatomic,weak) id<TSKSettingItemEditingControllerDelegate> editingDelegate;              //@synthesize editingDelegate=_editingDelegate - In the implementation block
+(id)multiValueControllerWithSettingItem:(id)arg1 ;
-(void)setEditingDelegate:(id<TSKSettingItemEditingControllerDelegate>)arg1 ;
-(id<TSKSettingItemEditingControllerDelegate>)editingDelegate;
-(void)_updateAppearance;
-(TSKSettingItem *)editingItem;
-(void)setEditingItem:(TSKSettingItem *)arg1 ;
-(id)_sortedAvailableValues;
-(id)_sortedLocalizedAvailableValues;
-(void)_sortItemsIfNeeded;
@end

