/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 22, 2018 at 11:13:55 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /System/Library/PrivateFrameworks/TVSettingKit.framework/TVSettingKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSFormatter.h>

@class NSArray, NSMapTable;

@interface TSKMappingFormatter : NSFormatter {

	NSArray* _inputs;
	NSMapTable* _mapping;

}

@property (nonatomic,copy) NSMapTable * mapping;                   //@synthesize mapping=_mapping - In the implementation block
@property (nonatomic,copy,readonly) NSArray * inputs;              //@synthesize inputs=_inputs - In the implementation block
-(NSArray *)inputs;
-(id)stringForObjectValue:(id)arg1 ;
-(NSMapTable *)mapping;
-(BOOL)getObjectValue:(out id*)arg1 forString:(id)arg2 errorDescription:(out id*)arg3 ;
-(void)setMapping:(NSMapTable *)arg1 ;
-(id)initWithInputs:(id)arg1 outputs:(id)arg2 ;
@end

