/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 22, 2018 at 11:13:54 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /System/Library/PrivateFrameworks/TVSettingKit.framework/TVSettingKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface TSKSettingItemUtilities : NSObject
+(id)localizedAvailableValuesForSettingItem:(id)arg1 ;
+(id)localizedDescriptionForItemInViewController:(id)arg1 atIndexPath:(id)arg2 ;
+(id)nextValueForSettingItem:(id)arg1 ;
+(id)localizedValueForSettingItem:(id)arg1 value:(id)arg2 ;
+(id)_formattedArray:(id)arg1 withFormatter:(id)arg2 ;
+(id)localizedValueForSettingItem:(id)arg1 ;
+(id)localizedDetailedAvailableValuesForSettingItem:(id)arg1 ;
@end

