/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 22, 2018 at 11:13:54 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /System/Library/PrivateFrameworks/TVSettingKit.framework/TVSettingKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol TSKSettingItemEditingControllerDelegate <NSObject>
@required
-(void)editingController:(id)arg1 didProvideValue:(id)arg2 forSettingItem:(id)arg3;
-(void)editingController:(id)arg1 didCancelForSettingItem:(id)arg2;

@end

