/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 22, 2018 at 11:13:54 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /System/Library/PrivateFrameworks/TVSettingKit.framework/TVSettingKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewHeaderFooterView.h"
#import "TSKCellUpdating.h"

@class UIActivityIndicatorView, NSString;

@interface TSKTableViewHeaderFooterView : UITableViewHeaderFooterView <TSKCellUpdating> {

	UIActivityIndicatorView* _spinnerView;
	BOOL _showSpinner;

}

@property (assign,nonatomic) BOOL showSpinner;                      //@synthesize showSpinner=_showSpinner - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)layoutSubviews;
-(void)setShowSpinner:(BOOL)arg1 ;
-(void)settingItem:(id)arg1 didUpdateMetadataWithGroup:(id)arg2 ;
-(BOOL)showSpinner;
@end

