/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 22, 2018 at 11:13:54 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /System/Library/PrivateFrameworks/TVSettingKit.framework/TVSettingKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <UIKit/UITableViewController.h>
#import "TSKTableViewDelegate.h"
#import "TSKPreviewing.h"

@protocol TSKPreviewingDelegate;
@class TSKTableView, UIView, TSKPreviewViewController, NSString;

@interface TSKTableViewController : UITableViewController <TSKTableViewDelegate, TSKPreviewing> {

	id<TSKPreviewingDelegate> _previewingDelegate;
	//TSKTableView* _tableView;
    UITableView * _tableView; //to keep compiler from complaining
    double _tableViewWidth;
	UIView* _tableContainerView;
	long long _tableViewStyle;
	TSKPreviewViewController* _defaultPreviewViewController;
	UIEdgeInsets _tableViewPadding;
	UIEdgeInsets _tableViewContentInsets;

}

@property (nonatomic,readonly) UIView * tableContainerView;                                          //@synthesize tableContainerView=_tableContainerView - In the implementation block
@property (nonatomic,readonly) long long tableViewStyle;                                             //@synthesize tableViewStyle=_tableViewStyle - In the implementation block
@property (nonatomic,readonly) UIEdgeInsets tableViewContentInsets;                                  //@synthesize tableViewContentInsets=_tableViewContentInsets - In the implementation block
@property (nonatomic,readonly) TSKPreviewViewController * defaultPreviewViewController;              //@synthesize defaultPreviewViewController=_defaultPreviewViewController - In the implementation block
@property (nonatomic,retain) UITableView * tableView;  //is really TSKTableView                      //@synthesize tableView=_tableView - In the implementation block
@property (assign,nonatomic) double tableViewWidth;                                                  //@synthesize tableViewWidth=_tableViewWidth - In the implementation block
@property (assign,nonatomic) UIEdgeInsets tableViewPadding;                                          //@synthesize tableViewPadding=_tableViewPadding - In the implementation block
//@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic,weak) id<TSKPreviewingDelegate> previewingDelegate;                    //@synthesize previewingDelegate=_previewingDelegate - In the implementation block
+(id)_productImage;
-(void)tableView:(id)arg1 didUpdateFocusInContext:(id)arg2 withAnimationCoordinator:(id)arg3 ;
-(void)loadView;
-(id)preferredFocusEnvironments;
//-(void)setTableView:(TSKTableView *)arg1 ;
//-(TSKTableView *)tableView;
-(void)viewDidLoad;
-(long long)tableViewStyle;
-(id)initWithStyle:(long long)arg1 ;
-(double)tableViewWidth;
-(void)setTableViewWidth:(double)arg1 ;
-(UIEdgeInsets)tableViewPadding;
-(void)setTableViewPadding:(UIEdgeInsets)arg1 ;
-(id<TSKPreviewingDelegate>)previewingDelegate;
-(id)defaultIndexPathForPreview;
-(id)previewForItemAtIndexPath:(id)arg1 ;
-(id)sourceViewForSlideTransition;
-(BOOL)hasFullscreenPreview;
-(void)setPreviewingDelegate:(id<TSKPreviewingDelegate>)arg1 ;
-(UIView *)tableContainerView;
-(UIEdgeInsets)tableViewContentInsets;
-(TSKPreviewViewController *)defaultPreviewViewController;
@end

