/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 22, 2018 at 11:13:55 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /System/Library/PrivateFrameworks/TVSettingKit.framework/TVSettingKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

//
#import <UIKit/UIView.h>

@class UIImage, UIImageView;

@interface TSKVibrantImageView : UIView {

	UIImage* _image;
	UIImageView* _imageView;

}

@property (nonatomic,readonly) UIImageView * imageView;              //@synthesize imageView=_imageView - In the implementation block
@property (nonatomic,readonly) UIImage * image;                      //@synthesize image=_image - In the implementation block
-(void)setImage:(UIImage *)arg1 ;
-(void)traitCollectionDidChange:(id)arg1 ;
-(id)initWithImage:(id)arg1 ;
-(CGSize)intrinsicContentSize;
-(UIImage *)image;
-(UIImageView *)imageView;
-(id)initWithImage:(id)arg1 identifier:(id)arg2 ;
@end

