/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 22, 2018 at 11:13:54 PM Mountain Standard Time
* Operating System: Version 11.3 (Build 15L211)
* Image Source: /System/Library/PrivateFrameworks/TVSettingKit.framework/TVSettingKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UIViewControllerAnimatedTransitioning <NSObject>
@optional
-(id)interruptibleAnimatorForTransition:(id)arg1;
-(void)animationEnded:(BOOL)arg1;

@required
-(double)transitionDuration:(id)arg1;
-(void)animateTransition:(id)arg1;

@end

